# Generated by Django 5.1.3 on 2024-11-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Pattern"
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                ("severity", models.IntegerField(default=1, verbose_name="Severity")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_regex",
                    models.BooleanField(
                        default=False, verbose_name="Is Regular Expression"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suspicious Pattern",
                "verbose_name_plural": "Suspicious Patterns",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.EmailField(max_length=254, verbose_name="Sender Email"),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sender Name"
                    ),
                ),
                ("subject", models.CharField(max_length=512, verbose_name="Subject")),
                ("content", models.TextField(verbose_name="Email Content")),
                (
                    "received_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Received Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("suspicious", "Suspicious"),
                            ("dangerous", "Dangerous"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="ML Confidence Score"),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(default=False, verbose_name="Is Quarantined"),
                ),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="Has Attachments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="email_attachments/", verbose_name="File"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content Type"),
                ),
                ("size", models.IntegerField(verbose_name="File Size (bytes)")),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="Is Suspicious"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
        migrations.CreateModel(
            name="EmailAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_prediction",
                    models.JSONField(
                        default=dict, verbose_name="ML Prediction Details"
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                (
                    "risk_score",
                    models.FloatField(default=0.0, verbose_name="Risk Score"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Analysis Notes")),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="emails.email",
                    ),
                ),
                (
                    "matched_patterns",
                    models.ManyToManyField(to="emails.suspiciouspattern"),
                ),
            ],
            options={
                "verbose_name": "Email Analysis",
                "verbose_name_plural": "Email Analyses",
            },
        ),
    ]
